---
- name: configure agents
  hosts: "{{ on_hosts | default('all') }}"
  roles:
  - volttron.deployment.set_defaults
  - volttron.deployment.ansible_venv
  - volttron.deployment.copy_agent_configs
  tasks:

  - name: install agents
    volttron.deployment.volttron_agent:
      volttron_home: "{{ volttron_home }}"
      volttron_venv: "{{ volttron_venv }}"
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      agent_vip_id: "{{ item.key }}"
      agent_spec: "{{ item.value }}"
      agent_configs_dir: "{{ host_configs_dir }}"
    loop: "{{ host_configuration['agents'] | default({}) | dict2items }}"
